apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-shell
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: market-data-shell
  template:
    metadata:
      labels:
        app: market-data-shell
    spec:
      containers:
        - image: augustoocc/market-data:latest
          name: market-data-shell
          ports:
            - containerPort: 80