#service 
apiVersion: v1
kind: Service
metadata:
  name: market-data-shell
spec:
  type: Nodeport
  ports:
    - name: http
      nodePort: 30531
      port: 82
      protocol: TCP
      targetPort: 8080
    - name: https
      nodePort: 32245
      port: 446
      protocol: TCP
      targetPort: 8080
  selector:
    app: market-data-shell